package deliveries
import("context";"time";"go.mongodb.org/mongo-driver/v2/bson")
type DispatchService struct{repo *Repository;offers *OfferRepository;plans *PlanRepository;riders RiderEligibility;nearby NearbyFinder;offerTTL time.Duration}
func NewDispatchService(r *Repository,o *OfferRepository,p *PlanRepository,re RiderEligibility,n NearbyFinder)*DispatchService{return &DispatchService{repo:r,offers:o,plans:p,riders:re,nearby:n,offerTTL:45*time.Second}}
type NearbyRiderEligibility interface{CanAppearNearby(context.Context,string)(bool,error)}
func(s *DispatchService)canReceiveDispatch(ctx context.Context,riderID string)(bool,error){if v,ok:=s.riders.(NearbyRiderEligibility);ok{return v.CanAppearNearby(ctx,riderID)};return s.riders.CanPublishLocation(ctx,riderID)}
func(s *DispatchService)Offer(ctx context.Context,deliveryID,riderID,senderID string)(AssignmentOffer,error){did,e:=bson.ObjectIDFromHex(deliveryID);if e!=nil{return AssignmentOffer{},ErrNotFound};rid,e:=bson.ObjectIDFromHex(riderID);if e!=nil{return AssignmentOffer{},ErrOffer};d,e:=s.repo.Find(ctx,did);if e!=nil{return AssignmentOffer{},e};sid,e:=bson.ObjectIDFromHex(senderID);if e!=nil||d.Sender.UserID!=sid{return AssignmentOffer{},ErrForbidden};if d.Status!=StatusRequested{return AssignmentOffer{},ErrState};ok,e:=s.canReceiveDispatch(ctx,rid.Hex());if e!=nil{return AssignmentOffer{},e};if !ok{return AssignmentOffer{},ErrForbidden};now:=time.Now().UTC();o:=AssignmentOffer{ID:bson.NewObjectID(),DeliveryID:did,RiderID:rid,Status:StatusOffered,CreatedAt:now,ExpiresAt:now.Add(s.offerTTL)};e=s.offers.Create(ctx,o);return o,e}
func(s *DispatchService)Accept(ctx context.Context,offerID,riderID string)(Public,error){oid,e:=bson.ObjectIDFromHex(offerID);if e!=nil{return Public{},ErrOffer};rid,e:=bson.ObjectIDFromHex(riderID);if e!=nil{return Public{},ErrForbidden};o,e:=s.offers.Find(ctx,oid);if e!=nil{return Public{},e};now:=time.Now().UTC();if now.After(o.ExpiresAt){return Public{},ErrOfferExpired};if o.RiderID!=rid||o.Status!=StatusOffered{return Public{},ErrOffer};ok,e:=s.canReceiveDispatch(ctx,rid.Hex());if e!=nil{return Public{},e};if !ok{return Public{},ErrForbidden};d,e:=s.repo.Find(ctx,o.DeliveryID);if e!=nil{return Public{},e};ok,e=s.repo.Transition(ctx,o.DeliveryID,StatusRequested,StatusAssigned,bson.M{"riderId":rid,"updatedAt":now},Event{DeliveryID:o.DeliveryID,Type:"rider_assignment_accepted",ActorID:rid,At:now});if e!=nil{return Public{},e};if !ok{return Public{},ErrState};if ok,e=s.offers.Respond(ctx,oid,rid,StatusOffered,StatusAssigned,now);e!=nil{return Public{},e}else if !ok{return Public{},ErrOffer};if plan,e:=s.plans.FindByDelivery(ctx,o.DeliveryID);e==nil{_,_=s.plans.ClearActiveOffer(ctx,plan.ID,oid,now);_ = s.plans.Complete(ctx,plan.ID,now)};d.Status=StatusAssigned;d.RiderID=&rid;d.UpdatedAt=now;return public(d),nil}
func(s *DispatchService)Decline(ctx context.Context,offerID,riderID string)error{oid,e:=bson.ObjectIDFromHex(offerID);if e!=nil{return ErrOffer};rid,e:=bson.ObjectIDFromHex(riderID);if e!=nil{return ErrForbidden};o,e:=s.offers.Find(ctx,oid);if e!=nil{return e};now:=time.Now().UTC();ok,e:=s.offers.Respond(ctx,oid,rid,StatusOffered,StatusDeclined,now);if e!=nil{return e};if !ok{return ErrOffer};return s.advanceAfterOffer(ctx,o,oid,now)}
func(s *DispatchService)ExpireAndAdvance(ctx context.Context,offerID string)error{oid,e:=bson.ObjectIDFromHex(offerID);if e!=nil{return ErrOffer};o,e:=s.offers.Find(ctx,oid);if e!=nil{return e};now:=time.Now().UTC();if now.Before(o.ExpiresAt){return ErrOffer};ok,e:=s.offers.Respond(ctx,oid,o.RiderID,StatusOffered,StatusExpired,now);if e!=nil{return e};if !ok{return nil};return s.advanceAfterOffer(ctx,o,oid,now)}
func(s *DispatchService)advanceAfterOffer(ctx context.Context,o AssignmentOffer,offerID bson.ObjectID,now time.Time)error{d,e:=s.repo.Find(ctx,o.DeliveryID);if e!=nil{return e};plan,e:=s.plans.FindByDelivery(ctx,o.DeliveryID);if e!=nil{return e};if d.Status!=StatusRequested{_,_=s.plans.ClearActiveOffer(ctx,plan.ID,offerID,now);_ = s.plans.Complete(ctx,plan.ID,now);return nil};if ok,e:=s.plans.ClearActiveOffer(ctx,plan.ID,offerID,now);e!=nil{return e}else if !ok{return nil};_,e=s.advance(ctx,&plan);if e==ErrNoNearbyRiders{return nil};return e}
func(s *DispatchService)SweepExpired(ctx context.Context,limit int)error{values,e:=s.offers.Expired(ctx,time.Now().UTC(),limit);if e!=nil{return e};for _,v:=range values{if e:=s.ExpireAndAdvance(ctx,v.ID.Hex());e!=nil{return e}};return nil}
