package deliveries
import("context";"errors";"sort";"time";"github.com/alumasinde/tuma254-api/internal/locations";"go.mongodb.org/mongo-driver/v2/bson")
var ErrNoNearbyRiders=errors.New("no eligible nearby riders")
type NearbyFinder interface{Nearby(context.Context,float64,float64,float64,int)([]locations.PublicRiderLocation,error)}
type Candidate struct{RiderID bson.ObjectID `bson:"riderId"`;DistanceMeters float64 `bson:"distanceMeters"`;ActiveDeliveries int64 `bson:"activeDeliveries"`;Score float64 `bson:"score"`}
type DispatchPlan struct{ID bson.ObjectID `bson:"_id,omitempty"`;DeliveryID bson.ObjectID `bson:"deliveryId"`;Candidates []Candidate `bson:"candidates"`;NextIndex int `bson:"nextIndex"`;ActiveOfferID *bson.ObjectID `bson:"activeOfferId,omitempty"`;Status string `bson:"status"`;CreatedAt time.Time `bson:"createdAt"`;UpdatedAt time.Time `bson:"updatedAt"`}
type NearbyDispatchInput struct{RadiusMeters float64 `json:"radius_meters,omitempty"`;CandidateLimit int `json:"candidate_limit,omitempty"`}
type DispatchResult struct{PlanID string `json:"plan_id"`;OfferID string `json:"offer_id,omitempty"`;RiderID string `json:"rider_id,omitempty"`;ExpiresAt *time.Time `json:"expires_at,omitempty"`;Candidates int `json:"candidates"`}
func(s *DispatchService) StartNearby(ctx context.Context,deliveryID string,in NearbyDispatchInput)(DispatchResult,error){did,e:=bson.ObjectIDFromHex(deliveryID);if e!=nil{return DispatchResult{},ErrNotFound};d,e:=s.repo.Find(ctx,did);if e!=nil{return DispatchResult{},e};if d.Method!=MethodNearby||d.Status!=StatusRequested{return DispatchResult{},ErrState};radius:=in.RadiusMeters;if radius<=0{radius=5000};limit:=in.CandidateLimit;if limit<=0{limit=12};if limit>50{limit=50};near,e:=s.nearby.Nearby(ctx,d.Pickup.Location.Coordinates[1],d.Pickup.Location.Coordinates[0],radius,limit);if e!=nil{return DispatchResult{},e};candidates:=make([]Candidate,0,len(near));for _,n:=range near{rid,e:=bson.ObjectIDFromHex(n.RiderID);if e!=nil{continue};ok,e:=s.riders.CanPublishLocation(ctx,n.RiderID);if e!=nil||!ok{continue};load,e:=s.repo.CountActiveForRider(ctx,rid);if e!=nil{return DispatchResult{},e};candidates=append(candidates,Candidate{RiderID:rid,DistanceMeters:n.DistanceMeters,ActiveDeliveries:load,Score:n.DistanceMeters+float64(load)*5000})};sort.SliceStable(candidates,func(i,j int)bool{return candidates[i].Score<candidates[j].Score});if len(candidates)==0{return DispatchResult{},ErrNoNearbyRiders};now:=time.Now().UTC();plan:=DispatchPlan{ID:bson.NewObjectID(),DeliveryID:did,Candidates:candidates,Status:"active",CreatedAt:now,UpdatedAt:now};if e:=s.plans.Create(ctx,plan);e!=nil{return DispatchResult{},e};offer,e:=s.advance(ctx,&plan);if e!=nil{return DispatchResult{},e};return DispatchResult{PlanID:plan.ID.Hex(),OfferID:offer.ID.Hex(),RiderID:offer.RiderID.Hex(),ExpiresAt:&offer.ExpiresAt,Candidates:len(candidates)},nil}
func(s *DispatchService) advance(ctx context.Context,plan *DispatchPlan)(AssignmentOffer,error){for plan.NextIndex<len(plan.Candidates){c:=plan.Candidates[plan.NextIndex];next:=plan.NextIndex+1;if ok,e:=s.plans.Advance(ctx,plan.ID,plan.NextIndex,next);e!=nil{return AssignmentOffer{},e}else if !ok{return AssignmentOffer{},ErrOffer};plan.NextIndex=next;ok,e:=s.riders.CanPublishLocation(ctx,c.RiderID.Hex());if e!=nil{return AssignmentOffer{},e};if !ok{continue};now:=time.Now().UTC();o:=AssignmentOffer{ID:bson.NewObjectID(),DeliveryID:plan.DeliveryID,RiderID:c.RiderID,Status:StatusOffered,CreatedAt:now,ExpiresAt:now.Add(s.offerTTL)};if e:=s.offers.Create(ctx,o);e!=nil{return AssignmentOffer{},e};if e:=s.plans.SetActiveOffer(ctx,plan.ID,o.ID,now);e!=nil{return AssignmentOffer{},e};return o,nil};_ = s.plans.Complete(ctx,plan.ID,time.Now().UTC());return AssignmentOffer{},ErrNoNearbyRiders}
