package deliveries
import("context";"errors";"go.mongodb.org/mongo-driver/v2/bson";"go.mongodb.org/mongo-driver/v2/mongo";"go.mongodb.org/mongo-driver/v2/mongo/options")
var ErrNotFound=errors.New("delivery not found")
type Repository struct{db *mongo.Database};func NewRepository(db *mongo.Database)*Repository{return &Repository{db}}
func(r *Repository)Create(ctx context.Context,d Delivery)error{_,e:=r.db.Collection("deliveries").InsertOne(ctx,d);return e}
func(r *Repository)Find(ctx context.Context,id bson.ObjectID)(Delivery,error){var d Delivery;e:=r.db.Collection("deliveries").FindOne(ctx,bson.M{"_id":id}).Decode(&d);if errors.Is(e,mongo.ErrNoDocuments){e=ErrNotFound};return d,e}
func(r *Repository)Transition(ctx context.Context,id bson.ObjectID,from,to string,set bson.M,e Event)(bool,error){set["status"]=to;res,err:=r.db.Collection("deliveries").UpdateOne(ctx,bson.M{"_id":id,"status":from},bson.M{"$set":set});if err!=nil{return false,err};if res.ModifiedCount==0{return false,nil};_,err=r.db.Collection("delivery_events").InsertOne(ctx,e);return true,err}
func(r *Repository)CountActiveForRider(ctx context.Context,id bson.ObjectID)(int64,error){return r.db.Collection("deliveries").CountDocuments(ctx,bson.M{"riderId":id,"status":bson.M{"$in":[]string{StatusAssigned,StatusAwaitingPickupOTP,StatusPickedUp,StatusInTransit,StatusAwaitingDeliveryOTP}}})}
func(r *Repository)ListForUser(ctx context.Context,id bson.ObjectID)([]Delivery,error){c,e:=r.db.Collection("deliveries").Find(ctx,bson.M{"sender.userId":id},options.Find().SetSort(bson.D{{Key:"createdAt",Value:-1}}));if e!=nil{return nil,e};defer c.Close(ctx);var out []Delivery;e=c.All(ctx,&out);return out,e}

func(r *Repository)RecordOTPFailure(ctx context.Context,id bson.ObjectID,field string,expected string,now time.Time,max int)(bool,bool,error){path:=field+".attempts";lock:=field+".lockedAt";filter:=bson.M{"_id":id,"status":expected,field+".verifiedAt":bson.M{"$exists":false},field+".lockedAt":bson.M{"$exists":false}};update:=bson.M{"$inc":bson.M{path:1},"$set":bson.M{"updatedAt":now}};res,e:=r.db.Collection("deliveries").UpdateOne(ctx,filter,update);if e!=nil||res.ModifiedCount==0{return false,false,e};var d Delivery;e=r.db.Collection("deliveries").FindOne(ctx,bson.M{"_id":id}).Decode(&d);if e!=nil{return true,false,e};var o *OTP;if field=="pickupOtp"{o=d.PickupOTP}else{o=d.DeliveryOTP};locked:=o!=nil&&o.Attempts>=max;if locked{_,e=r.db.Collection("deliveries").UpdateOne(ctx,bson.M{"_id":id},bson.M{"$set":bson.M{lock:now,"updatedAt":now}})};return true,locked,e}
func(r *Repository)CreateIncident(ctx context.Context,i Incident)error{_,e:=r.db.Collection("delivery_incidents").InsertOne(ctx,i);return e}
