package deliveries
import("context";"crypto/rand";"crypto/sha256";"encoding/hex";"errors";"fmt";"math/big";"strings";"time";"go.mongodb.org/mongo-driver/v2/bson")
var(ErrState=errors.New("invalid delivery state");ErrOTP=errors.New("invalid otp");ErrExpired=errors.New("otp expired");ErrForbidden=errors.New("forbidden");ErrOTPLocked=errors.New("otp locked");ErrOTPResend=errors.New("otp resend limit reached"))
type RiderEligibility interface{CanPublishLocation(context.Context,string)(bool,error)}
type Service struct{repo *Repository;riders RiderEligibility;otpTTL time.Duration;otpMaxAttempts int;otpMaxResends int}
func NewService(r *Repository,re RiderEligibility)*Service{return &Service{repo:r,riders:re,otpTTL:10*time.Minute,otpMaxAttempts:5,otpMaxResends:3}}
func(s *Service)Create(ctx context.Context,senderID string,in CreateInput)(Public,error){sid,e:=bson.ObjectIDFromHex(senderID);if e!=nil{return Public{},ErrNotFound};if !validStop(in.Pickup)||!validStop(in.Recipient)||strings.TrimSpace(in.Package.Description)==""||in.Package.WeightKG<=0{return Public{},errors.New("invalid delivery")};now:=time.Now().UTC();d:=Delivery{ID:bson.NewObjectID(),Sender:Party{UserID:sid},Pickup:in.Pickup,Recipient:in.Recipient,Package:in.Package,Method:in.Method,Status:StatusRequested,CreatedAt:now,UpdatedAt:now};if in.Method!=MethodFavourite&&in.Method!=MethodNearby{return Public{},errors.New("invalid dispatch method")};if in.Method==MethodFavourite{rid,e:=bson.ObjectIDFromHex(in.RiderID);if e!=nil{return Public{},errors.New("invalid rider")};ok,e:=s.riders.CanPublishLocation(ctx,rid.Hex());if e!=nil{return Public{},e};if !ok{return Public{},ErrForbidden};d.RiderID=&rid;d.Status=StatusAssigned};if e=s.repo.Create(ctx,d);e!=nil{return Public{},e};return public(d),nil}
func(s *Service)Assign(ctx context.Context,id,riderID,actor string)(Public,error){d,oid,rid,e:=s.load(ctx,id,riderID);if e!=nil{return Public{},e};if d.Status!=StatusRequested{return Public{},ErrState};ok,e:=s.riders.CanPublishLocation(ctx,rid.Hex());if e!=nil{return Public{},e};if !ok{return Public{},ErrForbidden};now:=time.Now().UTC()
ok,e=s.repo.Transition(ctx,oid,StatusRequested,StatusAssigned,bson.M{"riderId":rid,"updatedAt":now},Event{DeliveryID:oid,Type:"rider_assigned",ActorID:rid,At:now});if e!=nil{return Public{},e};if !ok{return Public{},ErrState};d.Status=StatusAssigned;d.RiderID=&rid;return public(d),nil}
func(s *Service)RequestPickupOTP(ctx context.Context,id,senderID string)(string,error){d,oid,_,e:=s.load(ctx,id,"");if e!=nil{return "",e};sid,e:=bson.ObjectIDFromHex(senderID);if e!=nil||d.Sender.UserID!=sid{return "",ErrForbidden};if d.Status!=StatusAssigned{return "",ErrState};otp,code,e:=newOTP(s.otpTTL);if e!=nil{return "",e};now:=time.Now().UTC();ok,e:=s.repo.Transition(ctx,oid,StatusAssigned,StatusAwaitingPickupOTP,bson.M{"pickupOtp":otp,"updatedAt":now},Event{DeliveryID:oid,Type:"pickup_otp_requested",ActorID:sid,At:now});if e!=nil{return "",e};if !ok{return "",ErrState};return code,nil}
func(s *Service)VerifyPickup(ctx context.Context,id,riderID,code string)(Public,error){d,oid,rid,e:=s.load(ctx,id,riderID);if e!=nil{return Public{},e};if d.Status!=StatusAwaitingPickupOTP{return Public{},ErrState};if d.RiderID==nil||*d.RiderID!=rid{return Public{},ErrForbidden};if e=verifyOTP(d.PickupOTP,code);e!=nil{now:=time.Now().UTC();_,locked,_:=s.repo.RecordOTPFailure(ctx,oid,"pickupOtp",StatusAwaitingPickupOTP,now,s.otpMaxAttempts);if locked{return Public{},ErrOTPLocked};return Public{},e};now:=time.Now().UTC();ok,e:=s.repo.Transition(ctx,oid,StatusAwaitingPickupOTP,StatusPickedUp,bson.M{"updatedAt":now,"pickupOtp.verifiedAt":now},Event{DeliveryID:oid,Type:"pickup_confirmed",ActorID:rid,At:now});if e!=nil{return Public{},e};if !ok{return Public{},ErrState};d.Status=StatusPickedUp;d.UpdatedAt=now;return public(d),nil}
func(s *Service)ResendPickupOTP(ctx context.Context,id,senderID string)(string,error){return s.resendOTP(ctx,id,senderID,"pickupOtp",StatusAwaitingPickupOTP,"pickup_otp_resent")}
func(s *Service)ResendDeliveryOTP(ctx context.Context,id,senderID string)(string,error){return s.resendOTP(ctx,id,senderID,"deliveryOtp",StatusAwaitingDeliveryOTP,"delivery_otp_resent")}
func(s *Service)resendOTP(ctx context.Context,id,senderID,field,status,event string)(string,error){d,oid,_,e:=s.load(ctx,id,"");if e!=nil{return "",e};sid,e:=bson.ObjectIDFromHex(senderID);if e!=nil||d.Sender.UserID!=sid{return "",ErrForbidden};if d.Status!=status{return "",ErrState};var old *OTP;if field=="pickupOtp"{old=d.PickupOTP}else{old=d.DeliveryOTP};if old==nil{return "",ErrOTP};if old.ResendCount>=s.otpMaxResends{return "",ErrOTPResend};otp,code,e:=newOTP(s.otpTTL);if e!=nil{return "",e};otp.ResendCount=old.ResendCount+1;otp.Version=old.Version+1;now:=time.Now().UTC();otp.LastSentAt=now;ok,e:=s.repo.Transition(ctx,oid,status,status,bson.M{field:otp,"updatedAt":now},Event{DeliveryID:oid,Type:event,ActorID:sid,At:now});if e!=nil{return "",e};if !ok{return "",ErrState};return code,nil}
func(s *Service)StartTransit(ctx context.Context,id,riderID string)(Public,error){d,oid,rid,e:=s.load(ctx,id,riderID);if e!=nil{return Public{},e};if d.Status!=StatusPickedUp{return Public{},ErrState};now:=time.Now().UTC();ok,e:=s.repo.Transition(ctx,oid,StatusPickedUp,StatusInTransit,bson.M{"updatedAt":now},Event{DeliveryID:oid,Type:"in_transit",ActorID:rid,At:now});if e!=nil{return Public{},e};if !ok{return Public{},ErrState};d.Status=StatusInTransit;d.UpdatedAt=now;return public(d),nil}
func(s *Service)RequestDeliveryOTP(ctx context.Context,id,senderID string)(string,error){d,oid,_,e:=s.load(ctx,id,"");if e!=nil{return "",e};sid,e:=bson.ObjectIDFromHex(senderID);if e!=nil||d.Sender.UserID!=sid{return "",ErrForbidden};if d.Status!=StatusInTransit{return "",ErrState};otp,code,e:=newOTP(s.otpTTL);if e!=nil{return "",e};now:=time.Now().UTC();ok,e:=s.repo.Transition(ctx,oid,StatusInTransit,StatusAwaitingDeliveryOTP,bson.M{"deliveryOtp":otp,"updatedAt":now},Event{DeliveryID:oid,Type:"delivery_otp_requested",ActorID:sid,At:now});if e!=nil{return "",e};if !ok{return "",ErrState};return code,nil}
func(s *Service)VerifyDelivery(ctx context.Context,id,riderID,code string)(Public,error){d,oid,rid,e:=s.load(ctx,id,riderID);if e!=nil{return Public{},e};if d.Status!=StatusAwaitingDeliveryOTP{return Public{},ErrState};if d.RiderID==nil||*d.RiderID!=rid{return Public{},ErrForbidden};if e=verifyOTP(d.DeliveryOTP,code);e!=nil{now:=time.Now().UTC();_,locked,_:=s.repo.RecordOTPFailure(ctx,oid,"deliveryOtp",StatusAwaitingDeliveryOTP,now,s.otpMaxAttempts);if locked{return Public{},ErrOTPLocked};return Public{},e};now:=time.Now().UTC();ok,e:=s.repo.Transition(ctx,oid,StatusAwaitingDeliveryOTP,StatusCompleted,bson.M{"updatedAt":now,"deliveryOtp.verifiedAt":now},Event{DeliveryID:oid,Type:"delivery_completed",ActorID:rid,At:now});if e!=nil{return Public{},e};if !ok{return Public{},ErrState};d.Status=StatusCompleted;d.UpdatedAt=now;return public(d),nil}
func(s *Service)ReportIncident(ctx context.Context,id,actorID,kind,reason string)error{d,oid,_,e:=s.load(ctx,id,"");if e!=nil{return e};aid,e:=bson.ObjectIDFromHex(actorID);if e!=nil{return ErrForbidden};kind=strings.TrimSpace(kind);reason=strings.TrimSpace(reason);if kind==""||reason==""{return errors.New("incident type and reason required")};return s.repo.CreateIncident(ctx,Incident{ID:bson.NewObjectID(),DeliveryID:oid,Type:kind,Reason:reason,ActorID:aid,Status:d.Status,CreatedAt:time.Now().UTC()})}
func(s *Service)Fail(ctx context.Context,id,riderID,reason string)(Public,error){d,oid,rid,e:=s.load(ctx,id,riderID);if e!=nil{return Public{},e};if d.Status==StatusCompleted||d.Status==StatusCancelled||d.Status==StatusFailed{return Public{},ErrState};reason=strings.TrimSpace(reason);if reason==""{return Public{},errors.New("failure reason required")};now:=time.Now().UTC();_ = s.repo.CreateIncident(ctx,Incident{ID:bson.NewObjectID(),DeliveryID:oid,Type:"delivery_failed",Reason:reason,ActorID:rid,Status:d.Status,CreatedAt:now});ok,e:=s.repo.Transition(ctx,oid,d.Status,StatusFailed,bson.M{"updatedAt":now,"failureReason":reason},Event{DeliveryID:oid,Type:"delivery_failed",ActorID:rid,At:now,Meta:map[string]string{"reason":reason}});if e!=nil{return Public{},e};if !ok{return Public{},ErrState};d.Status=StatusFailed;d.FailureReason=reason;d.UpdatedAt=now;return public(d),nil}
func(s *Service)Get(ctx context.Context,id string)(Public,error){d,_,_,e:=s.load(ctx,id,"");return public(d),e}
func(s *Service)load(ctx context.Context,id,rider string)(Delivery,bson.ObjectID,bson.ObjectID,error){oid,e:=bson.ObjectIDFromHex(id);if e!=nil{return Delivery{},oid,bson.NilObjectID,ErrNotFound};d,e:=s.repo.Find(ctx,oid);if e!=nil{return d,oid,bson.NilObjectID,e};var rid bson.ObjectID;if rider!=""{rid,e=bson.ObjectIDFromHex(rider);if e!=nil{return d,oid,rid,ErrForbidden}};return d,oid,rid,nil}
func validStop(x Stop)bool{return strings.TrimSpace(x.Address)!=""&&x.Location.Type=="Point"&&x.Location.Coordinates[0]>=-180&&x.Location.Coordinates[0]<=180&&x.Location.Coordinates[1]>=-90&&x.Location.Coordinates[1]<=90&&strings.TrimSpace(x.ContactName)!=""&&strings.TrimSpace(x.Phone)!=""}
func newOTP(ttl time.Duration)(OTP,string,error){n,e:=rand.Int(rand.Reader,big.NewInt(1000000));if e!=nil{return OTP{},"",e};code:=fmt.Sprintf("%06d",n.Int64());h:=sha256.Sum256([]byte(code));now:=time.Now().UTC();return OTP{Hash:hex.EncodeToString(h[:]),ExpiresAt:now.Add(ttl),MaxAttempts:5,LastSentAt:now,Version:1},code,nil}
func verifyOTP(o *OTP,code string)error{if o==nil{return ErrOTP};if o.LockedAt!=nil{return ErrOTPLocked};if time.Now().UTC().After(o.ExpiresAt){return ErrExpired};h:=sha256.Sum256([]byte(code));if hex.EncodeToString(h[:])!=o.Hash{return ErrOTP};return nil}
func public(d Delivery)Public{p:=Public{ID:d.ID.Hex(),Status:d.Status,Method:d.Method,Pickup:d.Pickup,Recipient:d.Recipient,Package:d.Package,CreatedAt:d.CreatedAt,UpdatedAt:d.UpdatedAt};if d.RiderID!=nil{p.RiderID=d.RiderID.Hex()};return p}
